Feature leads
MicroPyramid/react-crm pull request #3
Opened 2020-12-08 04:04 UTC by maheshguntur

1. Account Display, Add, Edit features 
2. Contact Display, Add, Edit features
3. Leads Display, Add, Edit features

2020-12-08 09:28 UTC, gopikrishnagurram commented on src/crm/Accounts/Accounts.js
> +                                  <th width="5%">ID</th>
Use Grid system instead of width.

2020-12-08 12:14 UTC, NagabrundaKodumuri commented on src/crm/Accounts/Accounts.js
> +                                  <th width="5%">ID</th>
Use grid system instead of width.

2020-12-08 12:21 UTC, NagabrundaKodumuri commented on src/crm/Accounts/Accounts.js
> +    console.log(results);
Remove console.log (s) because of that app performance will slow. Before pushing the code to git remove the unnecessary code.

2020-12-08 12:27 UTC, NagabrundaKodumuri commented on src/crm/Accounts/ViewAccount.js
> +    console.log(handleComment.comment);
Remove console.log (s) all over the app.

2020-12-08 12:38 UTC, NagabrundaKodumuri commented on src/crm/Contacts/Validations.js
> +  errors.last_name = (values.last_name) ? 'This field is required' : '';
Use formik for developing forms.

2020-12-17 10:36 UTC, NagabrundaKodumuri requested changes

2020-12-17 10:36 UTC, NagabrundaKodumuri commented on src/crm/Accounts/Accounts.js
> +                          }
check the condition once

2020-12-17 10:36 UTC, NagabrundaKodumuri commented on src/crm/Accounts/ViewAccount.js
> +                          </div>
check the title value

2020-12-17 10:36 UTC, NagabrundaKodumuri commented on src/crm/Contacts/AddContact.js
> +                                                      <option value="AF">Afghanistan</option>
change the country data to separate component.

2020-12-17 10:36 UTC, NagabrundaKodumuri commented on src/crm/Leads/Leads.js
> +                            lead.tags.map((tag, index) => {
Check the condition once , condition may breaks some times.

2020-12-17 10:36 UTC, NagabrundaKodumuri commented on src/crm/UIComponents/ActionButtons/DeleteActionButton.js
> +        method: 'DELETE',
use axios instead of fetch

2020-12-17 10:36 UTC, NagabrundaKodumuri commented on src/crm/Accounts/Validations.js
> +  errors.phone = (!values.phone.trim()) ? 'This field is required': '';
Check is phone field only accepting numbers or not.

2020-12-22 08:57 UTC, maheshguntur commented on src/crm/Accounts/Accounts.js
> +                                  <th width="5%">ID</th>
Updated column scopes  for table data and table header tags.

2020-12-22 08:57 UTC, maheshguntur commented on src/crm/Accounts/Accounts.js
> +    console.log(results);
Removed all console.log and unnecessary code

2020-12-22 08:58 UTC, maheshguntur commented on src/crm/Accounts/ViewAccount.js
> +    console.log(handleComment.comment);
removed all over application

2020-12-29 09:33 UTC, NagabrundaKodumuri approved these changes

2020-12-29 15:31 UTC, merged